/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.grupo4.manageclient.view;

/**
 *
 * @author anamo
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCreateP = new javax.swing.JButton();
        btnEditP = new javax.swing.JButton();
        btnDeleteP = new javax.swing.JButton();
        btnClearProduct = new javax.swing.JButton();
        txtIdProductField = new javax.swing.JTextField();
        lblNameProduct = new javax.swing.JLabel();
        lblSizeProduct = new javax.swing.JLabel();
        lblColorProduct = new javax.swing.JLabel();
        lblIdProduct = new javax.swing.JLabel();
        txtProductField = new javax.swing.JTextField();
        txtColorPField = new javax.swing.JTextField();
        lblUnitPrice = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        txtSizePField = new javax.swing.JTextField();
        txtUnitPriceField = new javax.swing.JTextField();
        txtStockField = new javax.swing.JTextField();
        btnSaveProduct = new java.awt.Button();

        jToolBar1.setRollover(true);

        btnCreateP.setText("Crear Producto");
        btnCreateP.setMaximumSize(new java.awt.Dimension(92, 24));
        btnCreateP.setMinimumSize(new java.awt.Dimension(92, 24));
        btnCreateP.setPreferredSize(new java.awt.Dimension(76, 24));
        btnCreateP.addActionListener(this::btnCreatePActionPerformed);
        jToolBar1.add(btnCreateP);

        btnEditP.setLabel("Editar Producto");
        jToolBar1.add(btnEditP);

        btnDeleteP.setText("Eliminar Producto");
        jToolBar1.add(btnDeleteP);

        btnClearProduct.setText("Limpiar Formulario");
        btnClearProduct.addActionListener(this::btnClearProductActionPerformed);
        jToolBar1.add(btnClearProduct);

        lblNameProduct.setText("Producto:");

        lblSizeProduct.setText("Talla:");

        lblColorProduct.setText("Color:");

        lblIdProduct.setText("Código:");

        txtProductField.addActionListener(this::txtProductFieldActionPerformed);

        txtColorPField.addActionListener(this::txtColorPFieldActionPerformed);

        lblUnitPrice.setText("Precio:");

        lblStock.setText("Stock:");

        txtSizePField.addActionListener(this::txtSizePFieldActionPerformed);

        txtUnitPriceField.addActionListener(this::txtUnitPriceFieldActionPerformed);

        txtStockField.addActionListener(this::txtStockFieldActionPerformed);

        btnSaveProduct.setLabel("Guardar");
        btnSaveProduct.setName(""); // NOI18N
        btnSaveProduct.addActionListener(this::btnSaveProductActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNameProduct)
                                    .addComponent(lblSizeProduct)
                                    .addComponent(lblColorProduct)
                                    .addComponent(lblUnitPrice)
                                    .addComponent(lblStock))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtColorPField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSizePField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnitPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnSaveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProduct))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameProduct)
                    .addComponent(txtProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSizeProduct)
                    .addComponent(txtSizePField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorProduct)
                    .addComponent(txtColorPField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitPrice)
                    .addComponent(txtUnitPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnSaveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        txtIdProductField.getAccessibleContext().setAccessibleName("Campo: Id del Producto");
        lblNameProduct.getAccessibleContext().setAccessibleName("Nombre del Producto");
        lblSizeProduct.getAccessibleContext().setAccessibleName("Talla del producto");
        lblColorProduct.getAccessibleContext().setAccessibleName("Color del producto");
        lblIdProduct.getAccessibleContext().setAccessibleName("Código del producto");
        txtProductField.getAccessibleContext().setAccessibleName("Campo: Nombre dle producto");
        txtColorPField.getAccessibleContext().setAccessibleName("Campo: color del producto");
        lblUnitPrice.getAccessibleContext().setAccessibleName("Precio del Producto");
        lblStock.getAccessibleContext().setAccessibleName("Stock del producto");
        txtSizePField.getAccessibleContext().setAccessibleName("Campo: Talla del producto");
        txtUnitPriceField.getAccessibleContext().setAccessibleName("Campo: precio del producto");
        txtStockField.getAccessibleContext().setAccessibleName("Campo: stock del producto");
        btnSaveProduct.getAccessibleContext().setAccessibleName("Guardar Producto");
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreatePActionPerformed

    private void btnClearProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearProductActionPerformed

    private void txtProductFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductFieldActionPerformed

    private void txtColorPFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorPFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorPFieldActionPerformed

    private void txtSizePFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizePFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizePFieldActionPerformed

    private void txtUnitPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceFieldActionPerformed

    private void txtStockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockFieldActionPerformed

    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearProduct;
    private javax.swing.JButton btnCreateP;
    private javax.swing.JButton btnDeleteP;
    private javax.swing.JButton btnEditP;
    private java.awt.Button btnSaveProduct;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblColorProduct;
    private javax.swing.JLabel lblIdProduct;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblSizeProduct;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JTextField txtColorPField;
    private javax.swing.JTextField txtIdProductField;
    private javax.swing.JTextField txtProductField;
    private javax.swing.JTextField txtSizePField;
    private javax.swing.JTextField txtStockField;
    private javax.swing.JTextField txtUnitPriceField;
    // End of variables declaration//GEN-END:variables
}
